[package]
name = "crdt-minesweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autosurgeon = "0.3.2"
automerge = "0.3.0"
