; The sine of an angle (specified in radians) can be computer by making use of the approximation sin x ~= x if x is sufficiently small, and the trigonometric identity:

; sin x = 3*sin(x/3) - 4*sin^3(x/3)

; to reduce the size of the arugment sin. (For purposes of this exercise, an angle is consdiered "sufficiently small" if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedrues:


(define (sine angle)
  (define (cube x)
    (* x x x))
  (define (p x)
    (- (* 3 x) (* 4 (cube x))))
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0))))

; PART A: How many times is procedure p applied when (sine 12.15) is evaluated?

; (sine 12.15)
; (p (sine (/ 12.15 3.0)))
; (p (sine 4.05))
; (p (p (sine (/ 4.05 3.0))))
; (p (p (sine 1.35)))
; (p (p (p (sine (/ 1.35 3.0)))))
; (p (p (p (sine 0.45))))
; (p (p (p (p (sine (/ 0.45 3.0))))))
; (p (p (p (p (sine 0.15)))))
; (p (p (p (p (p (sine (/ 0.15 3.0)))))))
; (p (p (p (p (p (sine 0.05))))))
; (p (p (p (p (p 0.05)))))
; ...

; ANSWER: 5 times

; PART BWhat is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

; ANSWER: For space, I think it's cube root? I'm not really sure: it's less than linear, but I'm not 100% certain how. I believe the same is true for the number of steps.
